package com.example.wemahostels.navigation

const val ROUTE_LOGIN="login"
const val  ROUTE_REGISTER="register"
const val ROUTE_HOME_ONE="adminhome"
const val ROUTE_HOME_TWO="clienthome"
const val ROUTE_ADD_HOUSE="addhouse"
const val ROUTE_VIEW_HOUSE="viewhouse"
const val ROUTE_VIEW_HOUSE_ADMIN="viewhouseadmin"
const val ROUTE_USER_PROFILE="userprofile"
const val ROUTE_UPDATE_USER_PROFILE="userprofileupdate"
const val ROUTE_EDIT_HOUSE="edithouse"
const val ROUTE_VIEW_CLIENT_ADMIN="viewusers"
const val ROUTE_EDIT_USERS="editusers"
const val ROUTE_VIEW_USERS="viewtheusers"
const val ROUTE_BOOK_HOUSE="bookhouse"
const val ROUTE_PAY="makepayment"
const val ROUTE_UPDATE_CLIENT="updateclient"
const val ROUTE_BOOKED="booked"
const val ROUTE_FEEDBACK="feedback"
const val ROUTE_SEARCH="search"

//const val ROUTE_VIEW_CLIENT="viewclients"
//const val ROUTE_UPDATE_CLIENT="updateclient"
//const val ROUTE_SPLASH="splashscreen"

